AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: API Gateway with DynamoDB integration using SAM

Resources:
  DDBFunction:
    Type: 'AWS::Serverless::Function'
    Connectors:
      MyConn:
        Properties:
          Destination:
            Type: AWS::DynamoDB::Table
            Arn: !GetAtt MyTable.Arn
          Permissions:
            - Read
            - Write
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: ./ddb
      Environment:
        Variables:
          TABLE_NAME: !Ref MyTable
      Description: GET Method for API Gateway with DynamoDB Integration
      MemorySize: 128
      Timeout: 30
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref MyApi

  MyTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: MyTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: false # sets for all methods
        # UsagePlan:  
        #   CreateUsagePlan: PER_API 

          

Outputs:
  DDBAPIGATEWAYApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"